{
  "abstract": [
    {
      "text": "Raises the receiver, causing program flow to jump to the local exception handler.",
      "type": "text"
    }
  ],
  "documentVersion": 0,
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.documentation/documentation/foundation",
        "doc://com.apple.documentation/documentation/foundation/errors_and_exceptions",
        "doc://com.apple.documentation/documentation/foundation/nsexception"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.documentation/documentation/foundation/nsexception/1416135-raise"
  },
  "kind": "symbol",
  "legacy_identifier": 1416135,
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSException(im)raise",
    "fragments": [
      {
        "kind": "text",
        "text": "func "
      },
      {
        "kind": "identifier",
        "text": "raise"
      },
      {
        "kind": "text",
        "text": "()"
      }
    ],
    "modules": [
      {
        "name": "Foundation"
      }
    ],
    "parent": {
      "title": "NSException"
    },
    "platforms": [
      {
        "current": "18.4",
        "introducedAt": "2.0",
        "name": "iOS"
      },
      {
        "current": "18.4",
        "introducedAt": "2.0",
        "name": "iPadOS"
      },
      {
        "current": "18.4",
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "current": "15.4",
        "introducedAt": "10.0",
        "name": "macOS"
      },
      {
        "current": "18.4",
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "current": "2.4",
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "current": "11.4",
        "introducedAt": "2.0",
        "name": "watchOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "instm",
    "title": "raise()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "raise"
            },
            {
              "kind": "text",
              "text": "()"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When there are no exception handlers in the exception handler stack, unless the exception is raised during the posting of a notification, this method calls the uncaught exception handler, in which last-minute logging can be performed. The program then terminates, regardless of the actions taken by the uncaught exception handler.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation": {
      "identifier": "doc://com.apple.documentation/documentation/foundation",
      "kind": "symbol",
      "role": "collection",
      "title": "Foundation",
      "type": "topic",
      "url": "/documentation/foundation"
    },
    "doc://com.apple.documentation/documentation/foundation/errors_and_exceptions": {
      "identifier": "doc://com.apple.documentation/documentation/foundation/errors_and_exceptions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Errors and Exceptions",
      "type": "topic",
      "url": "/documentation/foundation/errors_and_exceptions"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception": {
      "abstract": [
        {
          "text": "An object that represents a special condition that interrupts the normal flow of program execution.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSException",
      "type": "topic",
      "url": "/documentation/foundation/nsexception"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1409498-raise": {
      "abstract": [
        {
          "text": "Creates and raises an exception with the specified name, reason, and arguments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class func "
        },
        {
          "kind": "identifier",
          "text": "raise"
        },
        {
          "kind": "text",
          "text": "(NSExceptionName, "
        },
        {
          "kind": "identifier",
          "text": "format"
        },
        {
          "kind": "text",
          "text": ": String, "
        },
        {
          "kind": "identifier",
          "text": "arguments"
        },
        {
          "kind": "text",
          "text": ": CVaListPointer)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1409498-raise",
      "kind": "symbol",
      "role": "symbol",
      "title": "raise(_:format:arguments:)",
      "type": "topic",
      "url": "/documentation/foundation/nsexception/1409498-raise"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1414506-init": {
      "abstract": [
        {
          "text": "Initializes and returns a newly allocated exception object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": NSExceptionName, "
        },
        {
          "kind": "identifier",
          "text": "reason"
        },
        {
          "kind": "text",
          "text": ": String?, "
        },
        {
          "kind": "identifier",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": [AnyHashable : Any]?)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1414506-init",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(name:reason:userInfo:)",
      "type": "topic",
      "url": "/documentation/foundation/nsexception/1414506-init"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1416135-raise": {
      "abstract": [
        {
          "text": "Raises the receiver, causing program flow to jump to the local exception handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "raise"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1416135-raise",
      "kind": "symbol",
      "role": "symbol",
      "title": "raise()",
      "type": "topic",
      "url": "/documentation/foundation/nsexception/1416135-raise"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1569524-raise": {
      "abstract": [
        {
          "text": "A convenience method that creates and raises an exception.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "raise:format:"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1569524-raise",
      "kind": "symbol",
      "role": "symbol",
      "title": "raise:format:",
      "type": "topic",
      "url": "/documentation/foundation/nsexception/1569524-raise"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsexception/1409498-raise",
        "doc://com.apple.documentation/documentation/foundation/nsexception/1414506-init"
      ],
      "title": "Creating and Raising an NSException Object"
    },
    {
      "generated": false,
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsexception/1569524-raise"
      ],
      "title": "Related Documentation"
    }
  ],
  "variants": [
    {
      "paths": [
        "documentation/foundation/nsexception/1416135-raise"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    },
    {
      "paths": [
        "documentation/foundation/nsexception/1416135-raise"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
