{
  "abstract": [
    {
      "text": "An object that represents a special condition that interrupts the normal flow of program execution.",
      "type": "text"
    }
  ],
  "documentVersion": 0,
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.documentation/documentation/foundation",
        "doc://com.apple.documentation/documentation/foundation/errors_and_exceptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.documentation/documentation/foundation/nsexception"
  },
  "kind": "symbol",
  "legacy_identifier": 1416196,
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSException",
    "fragments": [
      {
        "kind": "text",
        "text": "class "
      },
      {
        "kind": "identifier",
        "text": "NSException"
      }
    ],
    "modules": [
      {
        "name": "Foundation"
      }
    ],
    "platforms": [
      {
        "current": "18.4",
        "introducedAt": "2.0",
        "name": "iOS"
      },
      {
        "current": "18.4",
        "introducedAt": "2.0",
        "name": "iPadOS"
      },
      {
        "current": "18.4",
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "current": "15.4",
        "introducedAt": "10.0",
        "name": "macOS"
      },
      {
        "current": "18.4",
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "current": "2.4",
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "current": "11.4",
        "introducedAt": "2.0",
        "name": "watchOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "cl",
    "title": "NSException"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSException"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception",
              "isActive": false,
              "type": "reference"
            },
            {
              "text": " to implement exception handling. An exception is a special condition that interrupts the normal flow of program execution. Each application can interrupt the program for different reasons. For example, one application might interpret saving a file in a directory that is write-protected as an exception. In this sense, the exception is equivalent to an error. Another application might interpret the user’s key-press (for example, Control-C) as an exception: an indication that a long-running process should abort.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation": {
      "identifier": "doc://com.apple.documentation/documentation/foundation",
      "kind": "symbol",
      "role": "collection",
      "title": "Foundation",
      "type": "topic",
      "url": "/documentation/foundation"
    },
    "doc://com.apple.documentation/documentation/foundation/1409609-nssetuncaughtexceptionhandler": {
      "abstract": [
        {
          "text": "Changes the top-level error handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "NSSetUncaughtExceptionHandler"
        },
        {
          "kind": "text",
          "text": "(((NSException) -> Void)?)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/1409609-nssetuncaughtexceptionhandler",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSetUncaughtExceptionHandler(_:)",
      "type": "topic",
      "url": "/documentation/foundation/1409609-nssetuncaughtexceptionhandler"
    },
    "doc://com.apple.documentation/documentation/foundation/1416853-nsgetuncaughtexceptionhandler": {
      "abstract": [
        {
          "text": "Returns the top-level error handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "NSGetUncaughtExceptionHandler"
        },
        {
          "kind": "text",
          "text": "() -> ((NSException) -> Void)?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/1416853-nsgetuncaughtexceptionhandler",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSGetUncaughtExceptionHandler()",
      "type": "topic",
      "url": "/documentation/foundation/1416853-nsgetuncaughtexceptionhandler"
    },
    "doc://com.apple.documentation/documentation/foundation/errors_and_exceptions": {
      "identifier": "doc://com.apple.documentation/documentation/foundation/errors_and_exceptions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Errors and Exceptions",
      "type": "topic",
      "url": "/documentation/foundation/errors_and_exceptions"
    },
    "doc://com.apple.documentation/documentation/foundation/nscopying": {
      "identifier": "doc://com.apple.documentation/documentation/foundation/nscopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception": {
      "abstract": [
        {
          "text": "An object that represents a special condition that interrupts the normal flow of program execution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSException"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSException",
      "type": "topic",
      "url": "/documentation/foundation/nsexception"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1409498-raise": {
      "abstract": [
        {
          "text": "Creates and raises an exception with the specified name, reason, and arguments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class func "
        },
        {
          "kind": "identifier",
          "text": "raise"
        },
        {
          "kind": "text",
          "text": "(NSExceptionName, "
        },
        {
          "kind": "identifier",
          "text": "format"
        },
        {
          "kind": "text",
          "text": ": String, "
        },
        {
          "kind": "identifier",
          "text": "arguments"
        },
        {
          "kind": "text",
          "text": ": CVaListPointer)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1409498-raise",
      "kind": "symbol",
      "role": "symbol",
      "title": "raise(_:format:arguments:)",
      "type": "topic",
      "url": "/documentation/foundation/nsexception/1409498-raise"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1410925-name": {
      "abstract": [
        {
          "text": "A string used to uniquely identify the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": NSExceptionName"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1410925-name",
      "kind": "symbol",
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/foundation/nsexception/1410925-name"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1412165-callstackreturnaddresses": {
      "abstract": [
        {
          "text": "The call return addresses related to a raised exception.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "callStackReturnAddresses"
        },
        {
          "kind": "text",
          "text": ": [NSNumber]"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1412165-callstackreturnaddresses",
      "kind": "symbol",
      "role": "symbol",
      "title": "callStackReturnAddresses",
      "type": "topic",
      "url": "/documentation/foundation/nsexception/1412165-callstackreturnaddresses"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1414506-init": {
      "abstract": [
        {
          "text": "Initializes and returns a newly allocated exception object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": NSExceptionName, "
        },
        {
          "kind": "identifier",
          "text": "reason"
        },
        {
          "kind": "text",
          "text": ": String?, "
        },
        {
          "kind": "identifier",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": [AnyHashable : Any]?)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1414506-init",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(name:reason:userInfo:)",
      "type": "topic",
      "url": "/documentation/foundation/nsexception/1414506-init"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1415537-reason": {
      "abstract": [
        {
          "text": "A string containing a “human-readable” reason for the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "reason"
        },
        {
          "kind": "text",
          "text": ": String?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1415537-reason",
      "kind": "symbol",
      "role": "symbol",
      "title": "reason",
      "type": "topic",
      "url": "/documentation/foundation/nsexception/1415537-reason"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1416135-raise": {
      "abstract": [
        {
          "text": "Raises the receiver, causing program flow to jump to the local exception handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "raise"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1416135-raise",
      "kind": "symbol",
      "role": "symbol",
      "title": "raise()",
      "type": "topic",
      "url": "/documentation/foundation/nsexception/1416135-raise"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1416845-callstacksymbols": {
      "abstract": [
        {
          "text": "An array containing the current call stack symbols.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "callStackSymbols"
        },
        {
          "kind": "text",
          "text": ": [String]"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1416845-callstacksymbols",
      "kind": "symbol",
      "role": "symbol",
      "title": "callStackSymbols",
      "type": "topic",
      "url": "/documentation/foundation/nsexception/1416845-callstacksymbols"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1418149-userinfo": {
      "abstract": [
        {
          "text": "A dictionary containing application-specific data pertaining to the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": [AnyHashable : Any]?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1418149-userinfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "userInfo",
      "type": "topic",
      "url": "/documentation/foundation/nsexception/1418149-userinfo"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexceptionname": {
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "NSExceptionName"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexceptionname",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExceptionName",
      "type": "topic",
      "url": "/documentation/foundation/nsexceptionname"
    },
    "doc://com.apple.documentation/documentation/foundation/nssecurecoding": {
      "identifier": "doc://com.apple.documentation/documentation/foundation/nssecurecoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.apple.documentation/documentation/foundation/nsuncaughtexceptionhandler": {
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSUncaughtExceptionHandler"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsuncaughtexceptionhandler",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUncaughtExceptionHandler",
      "type": "topic",
      "url": "/documentation/foundation/nsuncaughtexceptionhandler"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject": {
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.documentation/documentation/objectivec/nsobject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nscopying",
        "doc://com.apple.documentation/documentation/foundation/nssecurecoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "1651153",
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsexception/1409498-raise",
        "doc://com.apple.documentation/documentation/foundation/nsexception/1414506-init",
        "doc://com.apple.documentation/documentation/foundation/nsexception/1416135-raise"
      ],
      "kind": "taskGroup",
      "title": "Creating and Raising an NSException Object"
    },
    {
      "anchor": "1651228",
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsexception/1410925-name",
        "doc://com.apple.documentation/documentation/foundation/nsexception/1415537-reason",
        "doc://com.apple.documentation/documentation/foundation/nsexception/1418149-userinfo"
      ],
      "kind": "taskGroup",
      "title": "Querying an NSException Object"
    },
    {
      "anchor": "1651286",
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsexception/1412165-callstackreturnaddresses",
        "doc://com.apple.documentation/documentation/foundation/nsexception/1416845-callstacksymbols"
      ],
      "kind": "taskGroup",
      "title": "Getting Exception Stack Frames"
    },
    {
      "anchor": "2878673",
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsuncaughtexceptionhandler",
        "doc://com.apple.documentation/documentation/foundation/nsexceptionname"
      ],
      "kind": "taskGroup",
      "title": "Related Types"
    },
    {
      "anchor": "2878674",
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/1416853-nsgetuncaughtexceptionhandler",
        "doc://com.apple.documentation/documentation/foundation/1409609-nssetuncaughtexceptionhandler"
      ],
      "kind": "taskGroup",
      "title": "Functions"
    }
  ],
  "variants": [
    {
      "paths": [
        "documentation/foundation/nsexception"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    },
    {
      "paths": [
        "documentation/foundation/nsexception"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
